#INCLUDE 'TOTVS.CH'
#INCLUDE "tlpp-core.th"

Class xTesteJson

	//Data cJson
	Data jTeste
	Data jTeste2
	Data aTeste

	//public method new(cCpfCnpj) constructor
	public method new() constructor

EndClass

//Method new(cCpfCnpj as Character) Class xTesteJson
Method new() Class xTesteJson
	local i
	//::cJson := readJson('json_teste.json')
	private cJson := readJson('json_teste.json')

	::jTeste := JsonObject():New()
	//::jTeste:FromJson(::cJson)
	::jTeste:FromJson(cJson)

	::aTeste := {}
	for i := 1 to len(::jTeste)
		aAdd(::aTeste, ::jTeste[i])
	next

	cJson := readJson('json_teste2.json')

	::jTeste2 := JsonObject():New()
	//::jTeste2:FromJson(::cJson)
	::jTeste2:FromJson(cJson)

Return

User Function XTSTJS
	Local oObject

	oObject := xTesteJson():New()

Return

static function readJson(cFile)
	local oFile := FwFileReader():New('W:\ws_tds_vscode\tds-vscode-dev2\test\resources\projects\advpl\git\GIT-1274\' + cFile)
	local cJson := ''

	If(oFile:Open())
		aLines := oFile:GetAllLines()
		oFile:Close()
		aEval(aLines, { |x| cJson += x })
	else
		conout("Erro ao abrir arquivo: " + oFile:oErroLog:cDescription + ": " + oFile:oErroLog:message)

		return
	EndIf

return cJson
