#include "TOTVS.ch"
#include "RESTFUL.CH"

/*/{Protheus.doc} UserPasswordDialog
    @description
    This class is responsible for generating a dialog to ask for a username and password, 
    which will be used in the authentication process.

/*/
Class UserPasswordDialog from FWAdapterBaseV2
	private Method New() as Object
	Public Method GetUsername() as Character
	Public Method GetPassword() as Character
	Public Method SetUsername(cUsername)
	Public Method SetPassword(cPassword)

	Data cUsername As Character
	Data cPassword As Character
EndClass

/*/{Protheus.doc} New
    @description
    Creates an instance of the UserPasswordDialog class.

    @type		method
    @sample		oUserPassword := UserPasswordDialog():New()
/*/
Method New() Class UserPasswordDialog
	_Super:New("GET",.T.)
	Self:SetPath("/api/crm/v1/auth")
	Self:SetUsername("")
	Self:SetPassword("")
Return Self

/*/{Protheus.doc} GetUsername
    @description
    Returns the username entered by the user on the dialog.

    @type		method
    @sample		oUserPassword:GetUsername()
/*/
Method GetUsername() Class UserPasswordDialog
Return Self:cUsername

/*/{Protheus.doc} GetPassword
    @description
    Returns the password entered by the user on the dialog.

    @type		method
    @sample		oUserPassword:GetPassword()
/*/
Method GetPassword() Class UserPasswordDialog
Return Self:cPassword

/*/{Protheus.doc} SetUsername
    @description
    Sets the username to be sent to the API when authenticating.

    @type		method
    @param		cUsername, Character, Username to be set.
    @sample		oUserPassword:SetUsername("admin")
/*/
Method SetUsername(cUsername) Class UserPasswordDialog
	Self:cUsername := cUsername
Return Nil

/*/{Protheus.doc} SetPassword
    @description
    Sets the password to be sent to the API when authenticating.

    @type		method
    @param		cPassword, Character, Password to be set.
    @sample		oUserPassword:SetPassword("<PASSWORD>")
/*/
Method SetPassword(cPassword) Class UserPasswordDialog
	Self:cPassword := cPassword
Return Nil

/*/{Protheus.doc} get
    @description
    Sends a GET request to the API with the username and password provided on the dialog.
     If the credentials are valid, it returns a JSON containing the access token, expiration
      date and type of authorization (Basic or Bearer). Otherwise, it returns an error
       message indicating why the authentication failed.

    @type		method
    @sample		oUserPassword:get()
/*/
Method get() Class UserPasswordDialog
	Local oResponse := JsonObject():new() as Json
	Local jBody     := JsonObject():new() as Json
	Local cError    := "" as Character

	// Valida se os dados de usuário e senha foram informados
	If Empty(Self:cUsername)
		cError := STR0001 //"Usuário não informado."
	ElseIf Empty(Self:cPassword)
		cError := STR0002 //"Senha não informada."
	EndIf

	// Se houve erro na autenticação, ret

